### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DSBro** [xDefcon/sinusbot-scripts#10]
2017/11/13 00:22:02 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:22:03 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."

**Comment by xDefcon** [comment]
Can you please add a Full debug log? It seems that the bot does not have permissions to read clients' IP addresses, can you confirm that the bot does have that permission?

**Comment by DSBro** [comment]
see http://prntscr.com/h9neio

**Comment by xDefcon** [comment]
@DSBro can you see also this permission? https://i.imgur.com/HBEQImY.png

And can you send here a full instance log? (not only that 4 lines).
Thanks.

**Comment by DSBro** [comment]
run !antiproxy checkall result shtdown sinusbot ahahah 

2017/11/13 00:40:56 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:56 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:56 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:56 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:56 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] RESPONSE: {
    "success": false,
    "message": "The specified IP address is not valid."
}
2017/11/13 00:40:57 ae81de56 2bbfe2a1 PLUGIN AntiProxy :377  [DEBUG] Error in the API response. Is the API offline? Using cached data. URL: https://api.xdefcon.com/proxy/check/?ip=

2017/11/13 00:48:43 ae81de56 2bbfe2a1 WARN   TypeError: Cannot access member 'statusCode' of undefined
2017/11/13 00:48:43 ae81de56 2bbfe2a1 WARN   TypeError: Cannot access member 'statusCode' of undefined
2017/11/13 00:48:43 ae81de56 2bbfe2a1 WARN   TypeError: Cannot access member 'statusCode' of undefined

**Comment by xDefcon** [comment]
> @DSBro can you see if you set to true also this permission? https://i.imgur.com/HBEQImY.png

And please can you send a log when a users join the TS3 server? I need this kind of info to help you.
It seems that the bot can not see clients' IP addresses.

**Comment by DSBro** [comment]
sorry 
How do I find this file(log)?

**Comment by xDefcon** [comment]
Do the following:
First: Check if the boy has this permission https://i.imgur.com/HBEQImY.png
Second: Leave and rejoin your teamspeak server, and then give me the instance log. You should able to see something like "fired eventIPAddress"

**Comment by DSBro** [comment]
http://prntscr.com/h9nmcc

**Comment by DSBro** [comment]
lpe.ts3index.com

**Comment by xDefcon** [comment]
The problem was related to permissions. The bot did not have the correct permission: b_client_remoteaddress_view.

Solved directly with the user 👍
