### ISSUE TITLE
Idea | Give Servergroup to people with VPN

### ISSUE THREAD

**Issue by UltraTV** [xDefcon/sinusbot-scripts#16]
How about automatically give people with VPN a custom Servergroup

**Comment by JustAB0x** [comment]
@UltraTV @xDefcon would it be in line if that would be and additional punishment config option? Maybe making a PR.

**Comment by xDefcon** [comment]
@JustAB0x yes it would be ok

**Comment by JustAB0x** [comment]
PR is done.

**Comment by xDefcon** [comment]
Added in 2.3
