### ISSUE TITLE
False detections

### ISSUE THREAD

**Issue by Tyloendis** [xDefcon/sinusbot-scripts#17]
46.35.192.0 - 46.35.223.254
5.38.192.0 - 5.38.255.255
188.156.0.0 - 188.156.63.255
78.92.192.0 - 78.92.230.255
86.59.160.0 - 86.59.223.255
31.46.240.0 - 31.46.255.255
81.183.86.0 - 81.183.192.255
84.3.0.0 - 84.3.255.255
81.183.6.0 - 81.183.65.255

**Comment by Tigerpanzer02** [comment]
I have same Problem since 2 Days
That it detects mostly false

**Comment by Tyloendis** [comment]
The problem is, it literally detects the half of Hungary's IP ranges. Not really usable at this current sate. 
The idea is superb nevertheless.

**Comment by xDefcon** [comment]
Needs an analysis of the ASNs and IP ranges.
Definitely should not detect public ISPs as a proxy, will fix asap!

**Comment by Tigerpanzer02** [comment]
On my Teamspeak...
There are banned normal Users with a normal Ip
Would be nice if you fix as soon as possible ;)

**Comment by xDefcon** [comment]
@Tigerpanzer02 I'll fix this issue as soon as possible for sure, send here the censored IP addresses (hide last 8 bits, or block) to protect user's privacy.

**Comment by Tigerpanzer02** [comment]
85.0.156.208
176.10.115.147
178.162.197.90

**Comment by Tyloendis** [comment]
176.10.115.147 - Netname: "Cyberghost" 
Well you lucky bastard, you really cought a proxy user :D I only got fake proxy warnings :(

**Comment by Tigerpanzer02** [comment]
I know but the other not, i have seen it later 
Do not insult dude!

**Comment by Tyloendis** [comment]
I didn't mean to insult, I thought it was just a funny phrase :D 
I'm just really jealous I never got the chance to catch a real proxy user.

**Comment by Tigerpanzer02** [comment]
;)

**Comment by Tigerpanzer02** [comment]
@xDefcon 
Status?

**Comment by xDefcon** [comment]
The issue is fixed and the changes are now live.
