### ISSUE TITLE
User with proxy not detected

### ISSUE THREAD

**Issue by AndryGabry01** [xDefcon/sinusbot-scripts#23]
Today a user has connected to our ts with the intention to annoy our users, after we banned him continued to enter with several ip proxy, the bot after verifying them did not consider them as a proxy.
what do I have to do?
P.S If it can be useful the ip all started with 62.98.x.x
in case you need to sparrow the list of these ips privately to the developer

**Comment by xDefcon** [comment]
Confirmed what's written above.
