### ISSUE TITLE
Bot Detects permanently Clients as Proxy

### ISSUE THREAD

**Issue by klopek99** [xDefcon/sinusbot-scripts#25]
I updateted to Version 2.0 a few Minutes ago. The Bot escalated and Checked all Clients from the Server. He says permanently that everyone has an Proxy and Spams the Message. Without activating the Antibypass the Bot detects everyone as a bypasser.After that i activated it and deactivated, trying to stop the Antibypass but it keeps checking people. The Bot has enough Permissions, but cant retrieve the IP Adresses from Clients, thats why he dont write the IP into the Detected Proxy Message. Additionally he isn`t able to read the "Total Client Connections" and the "First connection" and says on every Client he has 0 Total Connections and the first connection was at 31 Dec 1969.

**Comment by xDefcon** [comment]
Wow, this seems strange to me. 

Can you ensure the bot has the correct permissions? Enable debug in the config and attach a log file here, I'll check better.

Thanks.

**Comment by klopek99** [comment]
Yes, i'm sure the bot has correct permissions he's already running over a few months without problems on the old Version.
Here is the Link with the Debug messages:
https://pastebin.com/CJXzdqUa
I felt free and made a Video how it looks like in the Chat:
https://youtu.be/8_TgICI2WLI
It's not speed upped, It's realtime.

**Comment by xDefcon** [comment]
Ouch, that is definitely a bug, now the problem is replicating it. Can you send a pic of the current AntiProxy configuration in the web interface? 
Thanks.

**Comment by xDefcon** [comment]
@klopek99 bump 👍

**Comment by IMmmKI** [comment]
Do you guys mind removing the pastebin link as it has client IPs, etc. :)

**Comment by xDefcon** [comment]
> Do you guys mind removing the pastebin link as it has client IPs, etc. :)

Totally true, removed links

**Comment by IMmmKI** [comment]
I am seeing the same error. 
Here is the screen of the settings. 

![image](https://user-images.githubusercontent.com/11090621/45494988-9e9c5380-b772-11e8-932e-12c4bd512ccf.png)

![image](https://user-images.githubusercontent.com/11090621/45495050-c1c70300-b772-11e8-8b81-2c457f7fb509.png)

**Comment by xDefcon** [comment]
2.1 should solve this problem, be sure to run the latest SinusBot version in combination with AntiProxy 2.1
