### ISSUE TITLE
IP ranges from an ISP getting picked up as a VPN

### ISSUE THREAD

**Issue by IMmmKI** [xDefcon/sinusbot-scripts#26]
I have an ISP that a lot of people use in South Africa which their IP ranges are being picked up as a VPN, please you assist. I did email you about this but I never heard anything back <3

e.g. of an IP - 165.73.24.11

Thanks

**Comment by xDefcon** [comment]
It is a new block that Afrihost added. It belongs to residential ADSLs. Fixed the issue.
