### ISSUE TITLE
IP ranges from an ISP getting picked up as a VPN

### ISSUE THREAD

**Issue by IMmmKI** [xDefcon/sinusbot-scripts#27]
I have another IP range that is being picked up incorrectly in South Africa. Thank you a lot for the assistance! 

e.g. of an IP - 129.205.143.249
Here is another IP - 105.184.20.123
Here are two more IPs that are being picked up incorrectly because of their ISP. 
196.251.18.97
160.226.238.19

Thanks

**Comment by xDefcon** [comment]
All the reported IP addresses except the first one resulted clean by the API,
Talking about the first one, i have to do some advanced scans, it seems a socks proxy.

**Comment by IMmmKI** [comment]
Thank you! :)
