### ISSUE TITLE
Missing privileges for script AntiProxy: [http]

### ISSUE THREAD

**Issue by Retardium** [xDefcon/sinusbot-scripts#32]
Hi, I only get this error message in the instance log, but I don't know exactly what it means. 
The TeamSpeak & Sinusbot privileges should not be the problem and ports 80 and 443 are also open.
For example, I can download and play MP3s directly from the net via sinusbots web panel. 
So internet access exists.

**Comment by Retardium** [comment]
I was stupid and used the wrong Sinusbot version / version of the script. :zipper_mouth_face:

**Comment by Pajaheh** [comment]
> 
> 
> I was stupid and used the wrong Sinusbot version / version of the script. 🤐

Hey, I have the same problem. What version you used?

**Comment by xDefcon** [comment]
> > I was stupid and used the wrong Sinusbot version / version of the script. 🤐
> 
> Hey, I have the same problem. What version you used?

Version 2.2 is for SinusBot 1.0
Version 2.1 is for SinusBot 0.14 and 0.15
