### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by solding** [xDefcon/sinusbot-scripts#8]
Hi, and thanks for the script @xDefcon. the v1.1 works great for me!
I have a few suggestions for the script that I made for my self, and thought it's maby something u want to add :)

**# 1 staff message** 
The returned client name is "linked" instead so u can easy click it and choose "find client in channel tree" etc.

This section:
```java
if (config.notifyOnDetection == 1) {
    sendMessageToStaff("[b][AntiProxy][/b] Detected Proxy on client: " + client.name() + "(" + client.uniqueID() + ") IP: " + client.getIPAddress());
}
```

and replace `client.name()` with `"[URL=client://" + client.id() + "/" + client.uniqueID() + "~" + client.name() + "]" + client.name() + "[/URL]"`

---

**# 2 Punishment Option**
Added a 4th option, to get punishment Message in chat. so u can have longer messages like: "text + link to admin on ts3 etc." or if u just prefer the client gets a chat message instead

This section:
```java
if (config.punishment == 0) {
    client.poke(config.punishmentMessage);
    debug("Sent poke to Client: " + client.name());
}
if (config.punishment == 1) {
    client.kick(config.punishmentMessage);
    debug("Kicked Client: " + client.name());
}
 if (config.punishment == 2) {
    client.ban(config.tempBanDuration, config.punishmentMessage.substring(0, 70));
    debug("Tempbanned Client: " + client.name() + " for " + config.tempBanDuration + " seconds.");
}

```

and add `if (config.punishment == 3) {
            client.chat(config.punishmentMessage);
            debug("Sent message to Client: " + client.name());
        }`
(and of course add 'chat' to options in punishment, so the new option is visible)

---

**Have one more** which is a bit related to the first suggestion, but nothing I could make my self.

Have custom staff message and be able to use "commands" like this in the text (**%TOTAL_CONNECTIONS% | %UID% | %CLIENT_ID% | %CLIENT_NAME% | %IP%** etc.)

So u can choose what to display and in witch order, use BBcode, and make link to the client. (like in my # 1 suggestion).
(add TotalConnections etc. (fast and easy way to se if it's a new user or an old user)

**Comment by xDefcon** [comment]
Thanks for suggestions, will be added in new version

**Comment by xDefcon** [comment]
@solding I may do not fully get your last suggestion, could you please check the newest version and open a new issue explaining your suggestion better? Thanks.
